Repository Alexhuszagh/rust-lexical, pull requests merged in 2024-09, with the labels that each got.

#110 Update CI and benchmark/test features.
  .github/workflows/Comprehensive.yml
  .github/workflows/Cross.yml
  .github/workflows/Features.yml
  .github/workflows/OSX.yml
  .github/workflows/Simple.yml
  .github/workflows/Valgrind.yml
  CHANGELOG
  README.md
  ci/check.sh
  ci/comprehensive.sh
  ci/test.sh
  docs/Development.md
  lexical-asm/src/lib.rs
  lexical-benchmark/algorithm/Cargo.toml
  lexical-benchmark/algorithm/bigint.rs
  lexical-benchmark/algorithm/division.rs
  lexical-benchmark/input.rs
  lexical-benchmark/parse-float/Cargo.toml
  lexical-benchmark/parse-float/black_box.rs
  lexical-benchmark/parse-integer/Cargo.toml
  lexical-benchmark/write-float/Cargo.toml
  lexical-benchmark/write-integer/Cargo.toml
  lexical-core/src/lib.rs
  lexical-parse-float/Cargo.toml
  lexical-parse-float/src/lib.rs
  lexical-parse-integer/Cargo.toml
  lexical-parse-integer/docs/Algorithm.md
  lexical-parse-integer/src/lib.rs
  lexical-util/etc/div128.py
  lexical-util/etc/step.py
  lexical-util/src/div128.rs
  lexical-util/src/iterator.rs
  lexical-util/src/lib.rs
  lexical-util/src/not_feature_format.rs
  lexical-util/tests/div128_tests.rs
  lexical-util/tests/iterator_tests.rs
  lexical-write-float/Cargo.toml
  lexical-write-float/docs/Algorithm.md
  lexical-write-float/etc/correctness/Cargo.toml
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/lib.rs
  lexical-write-float/src/table_dragonbox.rs
  lexical-write-integer/Cargo.toml
  lexical-write-integer/src/lib.rs
  lexical-write-integer/tests/api_tests.rs
  lexical/src/lib.rs
  scripts/check.sh
  setup.cfg
Labels: CI

#108 Don't extern alloc unless needed to avoid requiring global allocators in #[no_std] environments
  lexical/src/lib.rs
Labels: enhancement, no_std

#112 Improve inlining hints for better performance.
  CHANGELOG
  lexical-benchmark/README.md
  lexical-core/src/lib.rs
  lexical-parse-float/src/bellerophon.rs
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/lemire.rs
  lexical-parse-float/src/libm.rs
  lexical-parse-float/src/mask.rs
  lexical-parse-float/src/number.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/shared.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-float/src/table_bellerophon_decimal.rs
  lexical-parse-float/src/table_bellerophon_radix.rs
  lexical-parse-float/src/table_binary.rs
  lexical-parse-float/src/table_decimal.rs
  lexical-parse-float/src/table_radix.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/src/shared.rs
  lexical-size/bin/core_parse.rs
  lexical-util/etc/div128.py
  lexical-util/etc/step.py
  lexical-util/src/algorithm.rs
  lexical-util/src/assert.rs
  lexical-util/src/digit.rs
  lexical-util/src/div128.rs
  lexical-util/src/extended_float.rs
  lexical-util/src/feature_format.rs
  lexical-util/src/format.rs
  lexical-util/src/format_builder.rs
  lexical-util/src/format_flags.rs
  lexical-util/src/iterator.rs
  lexical-util/src/noskip.rs
  lexical-util/src/skip.rs
  lexical-util/src/step.rs
  lexical-write-float/etc/correctness/dragonbox/random.rs
  lexical-write-float/etc/correctness/dragonbox/roundtrip.rs
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/api.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/radix.rs
  lexical-write-float/src/shared.rs
  lexical-write-float/src/write.rs
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/table_binary.rs
  lexical-write-integer/src/table_radix.rs
  lexical-write-integer/src/write.rs
Labels: bug, regression

#90 Add CIFuzz Github action
  .github/workflows/Cifuzz.yml
Labels: CI

#113 Add benchmark CI workflow.
  .github/workflows/Benchmark.yml
Labels: regression, CI

#114 Fix integer parsing correctness issues.
  lexical-parse-integer/docs/Algorithm.md
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/src/api.rs
  lexical-parse-integer/src/compact.rs
  lexical-parse-integer/src/parse.rs
  lexical-parse-integer/src/shared.rs
  lexical-parse-integer/tests/algorithm_tests.rs
  lexical-parse-integer/tests/api_tests.rs
  lexical-parse-integer/tests/compact_tests.rs
  lexical-parse-integer/tests/issue_91_tests.rs
  lexical-util/src/num.rs
  scripts/asm.sh
Labels: bug, high priority

#116 Fix serializing -0.0 floats.
  lexical-write-float/file.diff
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/compact.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/radix.rs
  lexical-write-float/src/shared.rs
  lexical-write-float/tests/binary_tests.rs
  lexical-write-float/tests/hex_tests.rs
  lexical-write-float/tests/issue_94_tests.rs
Labels: bug

#117 Remove use of MaybeUninit in our float writers.
  .github/workflows/Miri.yml
  CHANGELOG
  lexical-write-float/src/compact.rs
  lexical-write-float/src/radix.rs
Labels: bug, high priority, A-sec

#122 Initial Littany of Safety Enhancements
  CHANGELOG
  CODE_OF_CONDUCT.md
  README.md
  docs/BinarySize.md
  docs/Development.md
  docs/DigitSeparators.md
  fuzz/README.md
  lexical-asm/README.md
  lexical-benchmark/README.md
  lexical-benchmark/algorithm/bigint.rs
  lexical-benchmark/compare.py
  lexical-benchmark/input.rs
  lexical-core/src/lib.rs
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/float.rs
  lexical-parse-float/src/index.rs
  lexical-parse-float/src/number.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-float/src/table_binary.rs
  lexical-parse-float/src/table_decimal.rs
  lexical-parse-float/src/table_radix.rs
  lexical-parse-float/tests/float_tests.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/src/shared.rs
  lexical-size/README.md
  lexical-util/src/algorithm.rs
  lexical-util/src/api.rs
  lexical-util/src/buffer.rs
  lexical-util/src/iterator.rs
  lexical-util/src/lib.rs
  lexical-util/src/noskip.rs
  lexical-util/src/num.rs
  lexical-util/src/skip.rs
  lexical-util/tests/algorithm_tests.rs
  lexical-util/tests/iterator_tests.rs
  lexical-write-float/file.diff
  lexical-write-float/src/api.rs
  lexical-write-float/src/compact.rs
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/radix.rs
  lexical-write-integer/src/table_binary.rs
  lexical-write-integer/src/table_radix.rs
  lexical/src/lib.rs
Labels: high priority, A-sec

#124 Improve performance when parsing integers.
  CHANGELOG
  ci/comprehensive.sh
  lexical-parse-float/etc/correctness/Cargo.toml
  lexical-parse-float/etc/correctness/test-parse-random/_common.rs
  lexical-parse-float/etc/correctness/test-parse-random/many-digits.rs
  lexical-parse-float/etc/correctness/test-parse-random/rand-f64.rs
  lexical-parse-float/etc/correctness/test-parse-random/runtests.py
  lexical-parse-float/etc/limits.py
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/src/api.rs
  lexical-parse-integer/src/compact.rs
  lexical-parse-integer/src/lib.rs
  lexical-parse-integer/src/options.rs
  lexical-parse-integer/src/parse.rs
  lexical-parse-integer/src/shared.rs
  lexical-parse-integer/tests/algorithm_tests.rs
  lexical-parse-integer/tests/api_tests.rs
  lexical-parse-integer/tests/compact_tests.rs
  lexical-util/src/algorithm.rs
  lexical-util/src/div128.rs
  lexical-util/src/feature_format.rs
  lexical-util/src/iterator.rs
  lexical-util/src/noskip.rs
  lexical-util/src/not_feature_format.rs
  lexical-util/src/num.rs
  lexical-util/src/skip.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/radix.rs
  lexical-write-float/src/write.rs
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/table_radix.rs
  lexical-write-integer/tests/api_tests.rs
Labels: enhancement

#125 Better documentation for our macros for maintainers.
  lexical-benchmark/compare.py
  lexical-benchmark/input.rs
  lexical-core/src/lib.rs
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/libm.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/shared.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-write-float/src/shared.rs
  lexical-write-float/tests/algorithm_tests.rs
  lexical-write-integer/tests/radix_tests.rs
Labels: documentation

#127 Document Internal Safety and Remove Most Unsafety
  ci/miri.sh
  ci/test.sh
  lexical-parse-float/src/parse.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-util/src/algorithm.rs
  lexical-util/src/assert.rs
  lexical-util/src/bf16.rs
  lexical-util/src/buffer.rs
  lexical-util/src/constants.rs
  lexical-util/src/digit.rs
  lexical-util/src/f16.rs
  lexical-util/src/iterator.rs
  lexical-util/src/lib.rs
  lexical-util/src/noskip.rs
  lexical-util/src/not_feature_format.rs
  lexical-util/src/skip.rs
  lexical-util/tests/algorithm_tests.rs
  lexical-util/tests/digit_tests.rs
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/compact.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/lib.rs
  lexical-write-integer/src/radix.rs
  lexical-write-integer/src/write.rs
  lexical-write-integer/tests/api_tests.rs
  lexical-write-integer/tests/decimal_tests.rs
  lexical-write-integer/tests/radix_tests.rs
Labels: high priority, A-sec

#129 Add more comprehensive miri coverage.
  CHANGELOG
  ci/miri.sh
  lexical-parse-float/etc/correctness/test-parse-golang/main.rs
  lexical-parse-float/etc/correctness/test-parse-random/_common.rs
  lexical-parse-float/etc/correctness/test-parse-random/many-digits.rs
  lexical-parse-float/etc/correctness/test-parse-random/rand-f64.rs
  lexical-parse-float/etc/correctness/test-parse-random/u64-pow2.rs
  lexical-parse-float/etc/correctness/test-parse-unittests/main.rs
  lexical-parse-float/etc/correctness/test-parse-unittests/rust_parse_tests.toml
  lexical-parse-float/etc/correctness/test-parse-unittests/strtod_tests.toml
Labels: A-sec, CI

#130 Fix unspecified behavior in LLVM and UB in Rust.
  lexical-core/src/lib.rs
  lexical/src/lib.rs
Labels: A-sec

#131 Fix correctness issue with skip iterators and short integer optimizations.
  lexical-parse-integer/src/algorithm.rs
Labels: bug

#132 Document Unsafety and Remove Compact Float Writing Unsafety
  README.md
  lexical-core/src/lib.rs
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/index.rs
  lexical-parse-float/src/lib.rs
  lexical-parse-float/src/libm.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-integer/src/lib.rs
  lexical-util/src/assert.rs
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/compact.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/lib.rs
  lexical-write-float/tests/compact_tests.rs
  lexical-write-integer/src/compact.rs
  lexical-write-integer/src/index.rs
  lexical-write-integer/src/lib.rs
Labels: A-sec

#134 Create SECURITY.md
  SECURITY.md
Labels: A-sec

#135 Refactor for Increased Safety without Performance Impacts
  .gitignore
  CHANGELOG
  README.md
  lexical-benchmark/parse-float/Cargo.toml
  lexical-benchmark/parse-float/black_box.rs
  lexical-benchmark/parse-float/denormal30.rs
  lexical-benchmark/parse-float/denormal6400.rs
  lexical-benchmark/write-float/Cargo.toml
  lexical-benchmark/write-float/special.rs
  lexical-core/Cargo.toml
  lexical-parse-float/Cargo.toml
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/fpu.rs
  lexical-parse-float/src/lib.rs
  lexical-parse-float/src/libm.rs
  lexical-parse-float/src/number.rs
  lexical-parse-integer/Cargo.toml
  lexical-util/src/algorithm.rs
  lexical-util/src/num.rs
  lexical-util/src/skip.rs
  lexical-write-float/Cargo.toml
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/api.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/compact.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/index.rs
  lexical-write-float/src/lib.rs
  lexical-write-float/src/radix.rs
  lexical-write-float/src/shared.rs
  lexical-write-float/src/write.rs
  lexical-write-float/tests/algorithm_tests.rs
  lexical-write-float/tests/binary_tests.rs
  lexical-write-float/tests/compact_tests.rs
  lexical-write-float/tests/hex_tests.rs
  lexical-write-float/tests/radix_tests.rs
  lexical-write-integer/Cargo.toml
  lexical-write-integer/src/compact.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/index.rs
  lexical/Cargo.toml
  scripts/unsafe.sh
Labels: A-sec

#139 Remove unsafe annotations for the options API.
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/options.rs
  lexical-parse-float/tests/options_tests.rs
  lexical-parse-integer/src/options.rs
  lexical-parse-integer/tests/options_tests.rs
  lexical-util/src/algorithm.rs
  lexical-util/src/iterator.rs
  lexical-write-float/src/options.rs
  lexical-write-float/tests/api_tests.rs
  lexical-write-float/tests/binary_tests.rs
  lexical-write-float/tests/hex_tests.rs
  lexical-write-float/tests/options_tests.rs
  lexical-write-integer/src/options.rs
Labels: enhancement

#141 Remove More Local Safety Invariants with Dedicated Functions
  CHANGELOG
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/lib.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/shared.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-float/tests/shared_tests.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-size/bin/write.rs
  lexical-util/src/buffer.rs
  lexical-util/src/iterator.rs
  lexical-util/src/lib.rs
  lexical-util/src/noskip.rs
  lexical-util/src/skip.rs
  lexical-util/tests/iterator_tests.rs
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/index.rs
Labels: A-sec

#142 Update documentation and make method names more expressive.
  README.md
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-util/src/iterator.rs
  lexical-util/src/lib.rs
  lexical-util/src/noskip.rs
  lexical-util/src/skip.rs
  lexical-util/tests/iterator_tests.rs
  lexical-write-float/src/write.rs
  lexical/src/lib.rs
Labels: documentation, A-sec

#143 Update docs for lexical-util.
  CHANGELOG
  lexical-util/Cargo.toml
  lexical-util/src/iterator.rs
  lexical-util/src/noskip.rs
  lexical-util/src/skip.rs
Labels: documentation

#150 Update documentation on correctness.
  README.md
Labels: documentation

#146 Increment the itoa benchmark versions.
  README.md
  lexical-benchmark/input.rs
  lexical-benchmark/parse-float/canada.rs
  lexical-benchmark/parse-float/earth.rs
  lexical-benchmark/parse-float/mesh.rs
  lexical-benchmark/write-integer/Cargo.toml
Labels: documentation

#155 Patch issue with incorrect parsing of leading zeros.
  lexical-parse-float/tests/issue_98_tests.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/tests/issue_98_tests.rs
Labels: bug, high priority, format

#156 Ensure leading invalid digits for floats correctly error.
  CHANGELOG
  README.md
  lexical-core/tests/issue_97_tests.rs
  lexical-parse-float/src/parse.rs
Labels: bug

#158 Fixes the `is_contiguous` check on digits iterators.
  CHANGELOG
  ci/test.sh
  lexical-util/src/skip.rs
Labels: bug, regression, high priority, format

#161 Improve the formatting API.
  CHANGELOG
  ci/comprehensive.sh
  clippy.toml
  lexical-parse-float/etc/correctness/Cargo.toml
  lexical-parse-float/etc/correctness/test-parse-golang/main.rs
  lexical-parse-float/etc/correctness/test-parse-random/rand-f64.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/tests/issue_96_tests.rs
  lexical-parse-float/tests/parse_tests.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/tests/issue_96_tests.rs
  lexical-util/src/feature_format.rs
  lexical-util/src/format_builder.rs
  lexical-util/src/iterator.rs
  lexical-util/src/noskip.rs
  lexical-util/src/not_feature_format.rs
  lexical-util/src/skip.rs
  lexical-util/tests/iterator_tests.rs
  lexical-util/tests/skip_tests.rs
Labels: bug, high priority, format
