Repository Alexhuszagh/rust-lexical, pull requests merged in 2024-12, with the labels that each got.

#181 Update development guides.
  docs/Development.md
  lexical-benchmark/algorithm/division.rs
Labels: documentation

#182 Add in spellchecking.
  .gitignore
  Cargo.toml
  docs/Development.md
  lexical-core/src/lib.rs
  lexical-parse-float/etc/correctness/test-parse-random/validate.rs
  lexical-parse-float/src/api.rs
  lexical-parse-float/src/bellerophon.rs
  lexical-parse-float/src/bigint.rs
  lexical-parse-float/src/binary.rs
  lexical-parse-float/src/float.rs
  lexical-parse-float/src/fpu.rs
  lexical-parse-float/src/lemire.rs
  lexical-parse-float/src/libm.rs
  lexical-parse-float/src/limits.rs
  lexical-parse-float/src/options.rs
  lexical-parse-float/src/parse.rs
  lexical-parse-float/src/shared.rs
  lexical-parse-float/src/slow.rs
  lexical-parse-float/src/table_binary.rs
  lexical-parse-integer/src/algorithm.rs
  lexical-parse-integer/src/api.rs
  lexical-parse-integer/src/options.rs
  lexical-util/src/digit.rs
  lexical-util/src/div128.rs
  lexical-util/src/format.rs
  lexical-util/src/noskip.rs
  lexical-util/tests/num_tests.rs
  lexical-write-float/etc/correctness/dragonbox/roundtrip.rs
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/api.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/compact.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/radix.rs
  lexical-write-float/src/shared.rs
  lexical-write-float/src/table_grisu.rs
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/lib.rs
  lexical-write-integer/src/table_decimal.rs
  lexical/src/lib.rs
  spellcheck.dic
  spellcheck.toml
Labels: documentation

#183 Ensure bisection artifacts are ignored.
  .gitignore
Labels: chore

#185 Fix Writing Integers with Non-Decimal Radices
  ci/comprehensive.sh
  ci/miri.sh
  ci/test.sh
  lexical-write-float/src/algorithm.rs
  lexical-write-float/src/binary.rs
  lexical-write-float/src/hex.rs
  lexical-write-float/src/shared.rs
  lexical-write-integer/Cargo.toml
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/compact.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/digit_count.rs
  lexical-write-integer/src/lib.rs
  lexical-write-integer/src/radix.rs
  lexical-write-integer/src/write.rs
  lexical-write-integer/tests/decimal_tests.rs
  lexical-write-integer/tests/digit_count_tests.rs
  lexical-write-integer/tests/radix_tests.rs
Labels: bug, regression, high priority, correctness, radix

#186 Add in optimizations for 2^N radix integer writing.
  lexical-write-integer/src/digit_count.rs
  lexical-write-integer/tests/digit_count_tests.rs
Labels: radix

#187 Optimize integer serialization with the jeaiii algorithm.
  lexical-parse-float/docs/Algorithm.md
  lexical-write-integer/docs/Algorithm.md
  lexical-write-integer/src/algorithm.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/jeaiii.rs
  lexical-write-integer/src/lib.rs
Labels: enhancement

#188 Add in jeaiii Optimizations for 64-bit Integers
  lexical-write-float/src/algorithm.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/jeaiii.rs
  lexical-write-integer/tests/api_tests.rs
Labels: enhancement

#189 Update CHANGELOG and README for 1.0.3 and later releases.
  CHANGELOG
  README.md
  assets/size0_nt.json
  assets/size0_posix.json
  assets/size1_nt.json
  assets/size1_posix.json
  assets/size2_nt.json
  assets/size2_posix.json
  assets/size3_nt.json
  assets/size3_posix.json
  assets/size_parse_pe_opt0_nt.svg
  assets/size_parse_pe_opt1_nt.svg
  assets/size_parse_pe_opt2_nt.svg
  assets/size_parse_pe_opt3_nt.svg
  assets/size_parse_pe_opts_nt.svg
  assets/size_parse_pe_optz_nt.svg
  assets/size_parse_stripped_opt0_posix.svg
  assets/size_parse_stripped_opt1_posix.svg
  assets/size_parse_stripped_opt2_posix.svg
  assets/size_parse_stripped_opt3_posix.svg
  assets/size_parse_stripped_opts_posix.svg
  assets/size_parse_stripped_optz_posix.svg
  assets/size_parse_unstripped_opt0_posix.svg
  assets/size_parse_unstripped_opt1_posix.svg
  assets/size_parse_unstripped_opt2_posix.svg
  assets/size_parse_unstripped_opt3_posix.svg
  assets/size_parse_unstripped_opts_posix.svg
  assets/size_parse_unstripped_optz_posix.svg
  assets/size_write_pe_opt0_nt.svg
  assets/size_write_pe_opt1_nt.svg
  assets/size_write_pe_opt2_nt.svg
  assets/size_write_pe_opt3_nt.svg
  assets/size_write_pe_opts_nt.svg
  assets/size_write_pe_optz_nt.svg
  assets/size_write_stripped_opt0_posix.svg
  assets/size_write_stripped_opt1_posix.svg
  assets/size_write_stripped_opt2_posix.svg
  assets/size_write_stripped_opt3_posix.svg
  assets/size_write_stripped_opts_posix.svg
  assets/size_write_stripped_optz_posix.svg
  assets/size_write_unstripped_opt0_posix.svg
  assets/size_write_unstripped_opt1_posix.svg
  assets/size_write_unstripped_opt2_posix.svg
  assets/size_write_unstripped_opt3_posix.svg
  assets/size_write_unstripped_opts_posix.svg
  assets/size_write_unstripped_optz_posix.svg
  assets/sizes_nt.json
  assets/sizes_posix.json
  assets/sizez_nt.json
  assets/sizez_posix.json
  assets/timings_all_nt.svg
  assets/timings_lexical-parse-float_nt.svg
  assets/timings_lexical-parse-integer_nt.svg
  assets/timings_lexical-write-float_nt.svg
  assets/timings_lexical-write-integer_nt.svg
  scripts/size.py
Labels: documentation

#192 Add patches and trait impls for f16 and bf16.
  CHANGELOG
  lexical-util/src/bf16.rs
  lexical-util/src/f16.rs
  lexical-util/src/lib.rs
  lexical-util/src/numtypes.rs
  lexical-write-float/src/algorithm.rs
  scripts/check.sh
  scripts/test.sh
Labels: bug

#194 Disable Valgrind except on workflow dispatch.
  .github/workflows/Valgrind.yml
Labels: CI

#193 Add in signed overloads for writing integers.
  CHANGELOG
  lexical-core/Cargo.toml
  lexical-parse-float/Cargo.toml
  lexical-parse-integer/Cargo.toml
  lexical-util/Cargo.toml
  lexical-write-float/Cargo.toml
  lexical-write-float/src/shared.rs
  lexical-write-integer/Cargo.toml
  lexical-write-integer/src/api.rs
  lexical-write-integer/src/decimal.rs
  lexical-write-integer/src/jeaiii.rs
  lexical-write-integer/src/write.rs
  lexical-write-integer/tests/decimal_tests.rs
  lexical/Cargo.toml
Labels: bug, high priority

#197 Fixes the comparison chain for NaN and equality in half floats.
  lexical-util/Cargo.toml
  lexical-util/src/bf16.rs
  lexical-util/src/f16.rs
  lexical-write-float/tests/api_tests.rs
Labels: bug, A-sec, half

#195 Add tests for formatting numeric limits
  lexical-core/tests/api_tests.rs
Labels: CI

#198 Migrate to using float16.
  lexical-core/Cargo.toml
  lexical-parse-float/Cargo.toml
  lexical-util/Cargo.toml
  lexical-util/src/bf16.rs
  lexical-util/src/f16.rs
  lexical-util/src/lib.rs
  lexical-util/src/numtypes.rs
  lexical-util/tests/bf16_tests.rs
  lexical-util/tests/f16_tests.rs
  lexical-write-float/Cargo.toml
  lexical/Cargo.toml
Labels: half

#199 Add validation for our docs in our CI pipelines.
  lexical-parse-float/src/options.rs
  lexical-util/src/iterator.rs
  lexical-write-float/src/options.rs
  lexical-write-integer/src/lib.rs
  scripts/check.sh
Labels: documentation, CI

#200 Add security audit to CI.
  .github/workflows/audit.yml
Labels: A-sec, CI
